 language: node_js
 node_js:
 - stable
 branches:
   only:
   - development
  notifications:
    email:
      recipients:
        - tarek.huawei@yahoo.com
      on_success: never
      on_failure: always